title: Alyvix
default_lang: en

author:
  name: Alyvix Team
  email: 'info@alyvix.com'

metadata:
    description: 'Alyvix: Eyes and hands like a human, with a stopwatch.'

redirects:
    'http://www.alyvix.com' : 'http://alyvix.com'
    'https://www.alyvix.com' : 'https://alyvix.com'
    '/alyvix' : '/'
    '/core' : '/'
    '/en': '/'
    '/de': '/'
    '/it': '/'
    '/synthetic-monitoring' : '/'
    '/visual-monitoring' : '/'
    '/pricing' : '/service'
    '/solution' : '/service'
    '/training' : '/service'
    '/about-us' : '/team'
    '/events' : '/team'
    '/support' : '/team'
    '/doc' : '/learn'
    '/success-stories' : '/blog'
